### ISSUE TITLE
Knaban Board Setup: Recipe App

### ISSUE THREAD

**Issue by egichuhis** [egichuhis/recipe_app_rails_group_project#18]
Hello, please review this Kanban board.

We are a team of 2, @egichuhis  and @AlselwiAisha 

We have divided the tasks fairly. Here is our [Kanban Board](https://github.com/users/egichuhis/projects/2/views/1) for your review.

**Comment by zeff96** [comment]
### Status: APPROVED :green_circle: 
Hi @egichuhis and @AlselwiAisha , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![congrats](https://media3.giphy.com/media/BPJmthQ3YRwD6QqcVD/200w.webp?cid=ecf05e47m27gwbn18jfhzuv7a5lhyxbno7996mu4qdniah1o&ep=v1_gifs_search&rid=200w.webp&ct=g)

## Highlights
:heavy_check_mark: Fairly distributed workload
:heavy_check_mark: All project requirements cards added
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
